openapi: 3.0.0
info:
  title: Astro Bookings Supplier API
  version: 1.0.0
  description: API for the Supplier Web Application of Astro Bookings

paths:
  /api/v1/auth/login:
    post:
      summary: Log in to supplier account
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"

  /api/v1/rockets:
    get:
      summary: Get all rockets for the supplier
      tags:
        - Rockets
      responses:
        "200":
          description: List of rockets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RocketDto"
    post:
      summary: Add a new rocket to the fleet
      tags:
        - Rockets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateRocketDto"
      responses:
        "201":
          description: Rocket created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RocketDto"

  /api/v1/rockets/{rocketId}:
    put:
      summary: Update rocket specifications
      tags:
        - Rockets
      parameters:
        - in: path
          name: rocketId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateRocketDto"
      responses:
        "200":
          description: Rocket updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RocketDto"

  /api/v1/launches:
    get:
      summary: Get all scheduled launches for the supplier
      tags:
        - Launches
      responses:
        "200":
          description: List of launches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/LaunchDto"
    post:
      summary: Schedule a new rocket launch
      tags:
        - Launches
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateLaunchDto"
      responses:
        "201":
          description: Launch scheduled successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LaunchDto"

  /api/v1/launches/{launchId}:
    put:
      summary: Update launch details
      tags:
        - Launches
      parameters:
        - in: path
          name: launchId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateLaunchDto"
      responses:
        "200":
          description: Launch updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LaunchDto"

  /api/v1/launches/{launchId}/status:
    put:
      summary: Update launch status (delay or abort)
      tags:
        - Launches
      parameters:
        - in: path
          name: launchId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateLaunchStatusDto"
      responses:
        "200":
          description: Launch status updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LaunchDto"

  /api/v1/launches/{launchId}/bookings:
    get:
      summary: View bookings for a specific launch
      tags:
        - Bookings
      parameters:
        - in: path
          name: launchId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of bookings for the launch
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BookingDto"

  /api/v1/launches/{launchId}/passenger-manifest:
    get:
      summary: Generate passenger manifest for a launch
      tags:
        - Launches
      parameters:
        - in: path
          name: launchId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Passenger manifest
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PassengerManifestDto"

  /api/v1/financial-reports:
    get:
      summary: View financial reports for launches
      tags:
        - Financial
      responses:
        "200":
          description: Financial report
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FinancialReportDto"

components:
  schemas:
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password

    LoginResponse:
      type: object
      properties:
        token:
          type: string
        user:
          $ref: "#/components/schemas/SupplierDto"

    SupplierDto:
      type: object
      properties:
        id:
          type: string
        companyName:
          type: string
        legalNumber:
          type: string
        legalAddress:
          type: string

    CreateRocketDto:
      type: object
      properties:
        name:
          type: string
        specifications:
          type: string
      required:
        - name
        - specifications

    UpdateRocketDto:
      type: object
      properties:
        name:
          type: string
        specifications:
          type: string

    RocketDto:
      type: object
      properties:
        id:
          type: string
        supplierId:
          type: string
        name:
          type: string
        specifications:
          type: string

    CreateLaunchDto:
      type: object
      properties:
        rocketId:
          type: string
        launchDate:
          type: string
          format: date-time
        destination:
          type: string
        capacity:
          type: integer
        pricePerSeat:
          type: number
      required:
        - rocketId
        - launchDate
        - destination
        - capacity
        - pricePerSeat

    UpdateLaunchDto:
      type: object
      properties:
        rocketId:
          type: string
        launchDate:
          type: string
          format: date-time
        destination:
          type: string
        capacity:
          type: integer
        pricePerSeat:
          type: number

    LaunchDto:
      type: object
      properties:
        id:
          type: string
        rocketId:
          type: string
        supplierId:
          type: string
        launchDate:
          type: string
          format: date-time
        destination:
          type: string
        capacity:
          type: integer
        pricePerSeat:
          type: number
        status:
          $ref: "#/components/schemas/LaunchStatus"

    UpdateLaunchStatusDto:
      type: object
      properties:
        status:
          $ref: "#/components/schemas/LaunchStatus"
      required:
        - status

    BookingDto:
      type: object
      properties:
        id:
          type: string
        customerId:
          type: string
        launchId:
          type: string
        numberOfSeats:
          type: integer
        status:
          $ref: "#/components/schemas/BookingStatus"
        totalAmount:
          type: number

    PassengerManifestDto:
      type: object
      properties:
        launchId:
          type: string
        launchDate:
          type: string
          format: date-time
        destination:
          type: string
        passengers:
          type: array
          items:
            $ref: "#/components/schemas/PassengerDto"

    PassengerDto:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        dateOfBirth:
          type: string
          format: date

    FinancialReportDto:
      type: object
      properties:
        totalRevenue:
          type: number
        platformFees:
          type: number
        netRevenue:
          type: number
        launchesRevenue:
          type: array
          items:
            type: object
            properties:
              launchId:
                type: string
              revenue:
                type: number

    LaunchStatus:
      type: string
      enum:
        - Scheduled
        - In Progress
        - Completed
        - Cancelled

    BookingStatus:
      type: string
      enum:
        - Pending
        - Confirmed
        - Cancelled

    InvoiceStatus:
      type: string
      enum:
        - Pending
        - Paid
        - Overdue
        - Cancelled

    InvoiceType:
      type: string
      enum:
        - CustomerBooking
        - SupplierFee

    PaymentMethod:
      type: string
      enum:
        - CreditCard
        - BankTransfer
        - PayPal
